plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

def runNumber = (System.getenv("GITHUB_RUN_NUMBER") ?: "1").toInteger()

android {
    namespace 'com.mobeen.launcher'
    compileSdk 34

    defaultConfig {
        applicationId "com.mobeen.launcher"
        minSdk 24
        targetSdk 34
        versionCode runNumber
        versionName "1.0.${runNumber}"
    }

    signingConfigs {
        release {
            def ksPath = System.getenv("KEYSTORE_PATH")
            if (ksPath) {
                storeFile file(ksPath)
                storePassword System.getenv("KEYSTORE_PASSWORD")
                keyAlias System.getenv("KEY_ALIAS")
                keyPassword System.getenv("KEY_PASSWORD")
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = '17'
    }
}
